version: '3.8'
services:
  ws-spam-email:
    image: ${DOCKER_REGISTRY}/${DOCKER_IMAGE}:ws-spam-model-updater-1.2.1e
    ports:
      - 5000:5000
  mongo-db:
    image: mongo
    # build: ./mongo-db-init
    # healthcheck:
    #   test: nc -z localhost 27017
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}
    volumes:
      - mongo-data-1.2c:/data/db

  mongoexpress:
    image:  mongo-express
    ports:
      - 8081:8081    
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USER}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongo-db
    restart: unless-stopped
    # depends_on:
    #  mongodb:
    #    condition: service_healthy

volumes:
  mongo-data-1.2c:
    driver: local
