version: '3.8'
services:
  app_email_scoring_container:
    container_name: app_email_scoring_container
    image: ${DOCKER_REGISTRY}/${DOCKER_REPOSITORY}:ws-email-scoring-${APP_VERSION}
    restart: always
    ports:
      - 5000:5000
    networks:
      - email-scoring-bridge
    env_file:
      - .env
      - .env.keys
      - .env.app.version
      - .env.app.name

networks:
  email-scoring-bridge:
    driver: bridge